/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;
/**
    * Simple dialog 
    * @author mefi
    */
public class Dialog extends javax.swing.JDialog {

    /**
     * Creates new form Dialog
     */
    public Dialog(String text) {
        initComponents();
        setVisible(true);
        pack();
        setTitle("Sbac");
        this.text.setText(text);
        this.text.setHorizontalAlignment(SwingConstants.CENTER);
        this.text.setVerticalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - Giovanni
	private void initComponents() {
		jPanel2 = new JPanel();
		text = new JLabel();
		confirm = new JButton();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		var contentPane = getContentPane();

		//======== jPanel2 ========
		{
			jPanel2.setBackground(Color.white);
			jPanel2.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border .EmptyBorder (
			0, 0 ,0 , 0) ,  "JFor\u006dDesi\u0067ner \u0045valu\u0061tion" , javax. swing .border . TitledBorder. CENTER ,javax . swing. border .TitledBorder
			. BOTTOM, new java. awt .Font ( "Dia\u006cog", java .awt . Font. BOLD ,12 ) ,java . awt. Color .
			red ) ,jPanel2. getBorder () ) ); jPanel2. addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override public void propertyChange (java .
			beans. PropertyChangeEvent e) { if( "bord\u0065r" .equals ( e. getPropertyName () ) )throw new RuntimeException( ) ;} } );

			//---- text ----
			text.setBackground(Color.white);
			text.setForeground(Color.black);

			//---- confirm ----
			confirm.setBackground(Color.black);
			confirm.setForeground(Color.white);
			confirm.setText("Confirm");
			confirm.addActionListener(e -> confirmActionPerformed(e));

			GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
			jPanel2.setLayout(jPanel2Layout);
			jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup()
					.addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(215, Short.MAX_VALUE)
						.addComponent(confirm)
						.addGap(205, 205, 205))
					.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addComponent(text, GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
						.addContainerGap(27, Short.MAX_VALUE))
			);
			jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup()
					.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addComponent(text, GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
						.addGap(20, 20, 20)
						.addComponent(confirm)
						.addContainerGap(20, Short.MAX_VALUE))
			);
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(0, 0, Short.MAX_VALUE))
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		pack();
		setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        dispose();
    }//GEN-LAST:event_confirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - Giovanni
	private JPanel jPanel2;
	private JLabel text;
	private JButton confirm;
    // End of variables declaration//GEN-END:variables
}
