/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle;
import models.Project;

/**
 * window used to pick a project 
 * @see javax.swing.JFrame
 * @author mefi
 */
public class ProjectPicker extends javax.swing.JFrame {
    private ArrayList<Project> projects;
    
    public ProjectPicker(ArrayList<Project> projects) {
        initComponents();
        setVisible(true);
        pack();
        setTitle("Sbac");
        this.projects = projects;
        //goBack.setIcon(new ImageIcon(getClass().getResource("/images/back.png")));
        populate();
    }
    
    private void populate() {
        DefaultListModel<Project> listModel = new DefaultListModel<>();
        try{
            for(Project p : projects)
                listModel.addElement(p);
            projectList.setModel(listModel);
        }catch(NullPointerException e){
            System.err.println("projects list empty");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - Giovanni
	private void initComponents() {
		jPanel1 = new JPanel();
		jScrollPane1 = new JScrollPane();
		projectList = new JList<>();
		jLabel1 = new JLabel();
		goBack = new JButton();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		var contentPane = getContentPane();

		//======== jPanel1 ========
		{
			jPanel1.setBackground(Color.white);
			jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border .EmptyBorder (
			0, 0 ,0 , 0) ,  "JF\u006frm\u0044es\u0069gn\u0065r \u0045va\u006cua\u0074io\u006e" , javax. swing .border . TitledBorder. CENTER ,javax . swing. border .TitledBorder
			. BOTTOM, new java. awt .Font ( "D\u0069al\u006fg", java .awt . Font. BOLD ,12 ) ,java . awt. Color .
			red ) ,jPanel1. getBorder () ) ); jPanel1. addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override public void propertyChange (java .
			beans. PropertyChangeEvent e) { if( "\u0062or\u0064er" .equals ( e. getPropertyName () ) )throw new RuntimeException( ) ;} } );

			//======== jScrollPane1 ========
			{

				//---- projectList ----
				projectList.setBackground(Color.black);
				projectList.setForeground(Color.white);
				projectList.setModel(new AbstractListModel<Project>() {
					Project[] values = {
							
					};
					@Override
					public int getSize() { return values.length; }
					@Override
					public Project getElementAt(int i) { return values[i]; }
				});
				projectList.setSelectionBackground(Color.yellow);
				projectList.addMouseListener(new MouseAdapter() {
					@Override
					public void mouseClicked(MouseEvent e) {
						projectListMouseClicked(e);
					}
				});
				jScrollPane1.setViewportView(projectList);
			}

			//---- jLabel1 ----
			jLabel1.setFont(new Font(Font.DIALOG, Font.BOLD, 18));
			jLabel1.setForeground(Color.black);
			jLabel1.setText("Projects ");

			//---- goBack ----
			goBack.setBorderPainted(false);
			goBack.setContentAreaFilled(false);
			goBack.setText("Go Back");
			goBack.addActionListener(e -> goBackActionPerformed(e));

			GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
			jPanel1.setLayout(jPanel1Layout);
			jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup()
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup()
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(35, 35, 35)
								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 309, GroupLayout.PREFERRED_SIZE))
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(150, 150, 150)
								.addComponent(jLabel1)))
						.addContainerGap(54, Short.MAX_VALUE))
					.addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(goBack)
						.addGap(23, 23, 23))
			);
			jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup()
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(29, 29, 29)
						.addComponent(jLabel1)
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(goBack)
						.addContainerGap(41, Short.MAX_VALUE))
			);
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		pack();
		setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void projectListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectListMouseClicked
        Project p = projectList.getSelectedValue();
        dispose();
        new CommitPicker(p);
    }//GEN-LAST:event_projectListMouseClicked

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new Download();
    }//GEN-LAST:event_goBackActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - Giovanni
	private JPanel jPanel1;
	private JScrollPane jScrollPane1;
	private JList<Project> projectList;
	private JLabel jLabel1;
	private JButton goBack;
    // End of variables declaration//GEN-END:variables
}
